### ISSUE TITLE
v0.0.27 + Hass 0.117.4 + Tasmota 9.0.0.3 - Python error

### ISSUE THREAD

**Issue by marknl** [emontnemery/hatasmota#33]
1. Updates Hass to 0.117.4
2. Flashed a light to 9.0.0.3
3. Ran `docker exec -ti homeassistant pip install -U hatasmota` to update to v0.0.27.

I'm receiving this error:
```
2020-11-05 01:05:14 ERROR (MainThread) [homeassistant.util.logging] Exception in discovery_message_received when handling msg on 'tasmota/discovery/D8F15B0DC328/config': '{"ip":"192.168.1.152","dn":"Spot02","fn":["Spot02",null,null,null,null,null,null,null],"hn":"tasmota_0DC328-0808","mac":"D8F15B0DC328","md":"ZolderGU10","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"9.0.0.3","t":"tasmota_0DC328","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[2,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null],"btn":[0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0},"lk":1,"lt_st":5,"ver":1}'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/hatasmota/discovery.py", line 158, in discovery_message_received
payload = TasmotaDiscoveryMsg(json.loads(payload))
File "/usr/local/lib/python3.8/site-packages/hatasmota/discovery.py", line 117, in __init__
config = TASMOTA_DISCOVERY_SCHEMA(config)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['if']
```

Seems to be related to https://github.com/emontnemery/hatasmota/blob/master/hatasmota/discovery.py#L92

**Comment by effelle** [comment]
Thanks for reporting. 
We are aware of the bug and was already addressed on our side. The fix will be available on Home Assistant BugFix 0.117.5.

**Comment by emontnemery** [comment]
@marknl FYI this is (hopefully) fixed in hatasmota 0.0.25.1, which is compatible with HA 0.117.x

To change version: `docker exec -ti homeassistant pip install hatasmota==0.0.25.1`, however HA will downgrade it to 0.0.25 when it starts.
Maybe you can edit homeassistant/components/tasmota/manifest.json, or start HA with `--skip-pip` option to prevent HA from downgrading the package.

**Comment by marknl** [comment]
@emontnemery Thanks for the tip. I tried 0.0.25.1 with HA 0.117.4, no dice. Still the error about data["if"]. To be clear, I'm only running that docker exec command and then in the GUI I reload the Tasmota (beta) integration. After that I see this error in the log again. I see Tasmota 9.1.0 was just released and HA 0.117.5 as well. I'll test with those. If the problem still occurs I'll report back.

**Comment by emontnemery** [comment]
> To be clear, I'm only running that docker exec command and then in the GUI I reload the Tasmota (beta) integration.
That won't work unfortunately, HA also needs to be restarted. Anyhow, let's hope 0.117.5 does it!

**Comment by marknl** [comment]
> That won't work unfortunately, HA also needs to be restarted. Anyhow, let's hope 0.117.5 does it!

Aaaaah, ok, edited manifest.json, then restarted HA, tasmota devices showed up with the direct integration, noice!!! ;-)
